pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/robel75/alx-backend-python.git',
                    branch: 'main'
            }
        }

        stage('Setup Python') {
            steps {
                bat 'python -m venv %VENV_DIR%'
                bat '%VENV_DIR%\\Scripts\\pip install --upgrade pip'
                bat '%VENV_DIR%\\Scripts\\pip install -r messaging_app\\requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat '%VENV_DIR%\\Scripts\\pytest messaging_app --junitxml=report.xml'
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'report.xml', fingerprint: true
        }
    }
}
