#!/bin/bash

set -e

kubectl apply -f messaging_app/blue_deployment.yaml

kubectl apply -f messaging_app/green_deployment.yaml

kubectl apply -f messaging_app/kubeservice.yaml

kubectl get pods

GREEN_PODS=$(kubectl get pods -l app=messaging-app,version=green -o jsonpath="{.items[*].metadata.name}")

for pod in $GREEN_PODS; do
  echo "Logs for $pod:"
  kubectl logs $pod
done
